version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    vendor: "true"
    directory: "/"
    schedule:
      interval: "weekly"
