name: Terraform provider lint
on:
  push:
    paths:
      - '**.go'
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
jobs:
  tfproviderlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
    - uses: bflad/tfproviderlint-github-action@master # TSCCR: no entry for repository "bflad/tfproviderlint-github-action"
      with:
        args: ./...
